global:
  rollingUpdate: {}
  image: {}

# image setting loadding order: (from higher priority to lower priority)
# - Values.image.x
# - Values.defaultImage.x
# You can set `imagePullSecret` value to `false` (bool) to reset the value (see example below)

defaultImage:
  repository: ghcr.io/magda-io
  pullPolicy: IfNotPresent
  imagePullSecret: false

image:
  name: "magda-preview-map"
  # repository:
  # tag:
  # pullPolicy:
  # imagePullSecret:

# -- no. of initial replicas of the deployment
replicas: 1

autoscaler:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
resources:
  requests:
    cpu: 50m
    memory: 200Mi
  limits:
    cpu: 250m

clientConfig:
  # -- Exact origins allowed to embed the preview map and send start data. Same-origin parents are always allowed.
  parentMessageAllowedOrigins: []

serverConfig:
  port: 6110
  allowProxyFor:
    - nicta.com.au
    - gov.au
    - csiro.au
    - arcgis.com
    - argo.jcommops.org
    - www.abc.net.au
    - geoserver.aurin.org.au
    - mapsengine.google.com
    - s3-ap-southeast-2.amazonaws.com
    - adelaidecitycouncil.com
    - www.dptiapps.com.au
    - geoserver-123.aodn.org.au
    - geoserver.imos.org.au
    - nci.org.au
    - static.nationalmap.nicta.com.au
    - githubusercontent.com
    - gov
    - gov.uk
    - gov.nz
    - sample.aero3dpro.com.au
