global:
  rollingUpdate: {}
  image: {}

# image setting loadding order: (from higher priority to lower priority)
# - Values.image.x
# - Values.global.image.x
# - Values.defaultImage.x
# You can set `imagePullSecret` value to `false` (bool) to reset the value (see example below)

defaultImage:
  repository: docker.io/data61
  pullPolicy: IfNotPresent
  imagePullSecret: false

image:
  name: "magda-preview-map"
  # repository:
  # tag:
  # pullPolicy:
  # imagePullSecret:

# -- no. of initial replicas of the deployment
replicas: 1

autoscaler:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
resources:
  requests:
    cpu: 50m
    memory: 200Mi
  limits:
    cpu: 250m
