apiVersion: apps/v1
kind: Deployment
metadata:
  name: preview-map
spec:
  replicas: {{ .Values.replicas | default 1 }}
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable | default 0 }}
  selector:
    matchLabels:
      service: preview-map
  template:
    metadata:
      labels:
        service: preview-map
    spec:
      containers:
      - name: preview-map
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- if .Values.global.enableLivenessProbes }}
        livenessProbe:
          httpGet:
            path: ""
            port: 6110
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
{{- end }}
        env:
        - name: NODE_ENV
          value: production
        image: {{ template "dockerimage" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.image.pullPolicy }}
